apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.103
      user: jw
      port: 22
      keyPath: /home/joel/.ssh/id_rsa
    role: single
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: stable
              url: https://charts.helm.sh/stable
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            charts:
            - name: prometheus-stack
              chartname: prometheus-community/prometheus
              version: "25.26.0"
              values: |
                alertmanager:
                  persistentVolume:
                    enabled: false
                server:
                  persistentVolume:
                    enabled: false
              namespace: default
