apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.103
      user: jw
      port: 22
      keyPath: /home/joel/.ssh/id_rsa
    role: single
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: stable
              url: https://charts.helm.sh/stable
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            - name: openebs-internal
              url: https://openebs.github.io/charts
            charts:
            - name: openebs
              chartname: openebs-internal/openebs
              version: "3.9.0"
              namespace: openebs
              order: 1
              values: |
                localprovisioner:
                  hostpathClass:
                    enabled: true
                    isDefaultClass: true
            - name: prometheus-stack
              chartname: prometheus-community/prometheus
              version: "25.26.0"
              namespace: default
              values: |
                server:
                  persistentVolume:
                    enabled: true
                    storageClass: "openebs-hostpath"
                    size: 10Gi

                    ------

                    
                  extraScrapeConfigs: |
                    - job_name: 'kube-state-metrics'
                      kubernetes_sd_configs:
                        - role: endpoints
                      relabel_configs:
                        - source_labels: [__meta_kubernetes_service_label_app]
                          action: keep
                          regex: kube-state-metrics
                    - job_name: 'node-exporter'
                      kubernetes_sd_configs:
                        - role: node
                      relabel_configs:
                        - action: labelmap
                          regex: __meta_kubernetes_node_label_(.+)
                        - target_label: __address__
                          replacement: kubernetes.default.svc:9100
                        - source_labels: [__meta_kubernetes_node_name]
                          target_label: instance
