apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.103
      user: jw
      port: 22
      keyPath: /home/joel/.ssh/id_rsa
    role: single
  k0s:
    config:
      extensions:
        helm:
          repositories:
          - name: stable
            url: https://charts.helm.sh/stable
